---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  get-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/getVersion.yml@0.3.0
    with:
      metadataFile: 'metadata.json'
      metadataPath: .
  docker-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerLint.yml@0.3.0
    with:
      dockerfilePath: 'docker/Dockerfile'
    needs: get-version
  sonar-scan:
    uses: GrabAByte/github-devops-workflows/.github/workflows/sonarScan.yml@0.3.0
    secrets:
      WORKFLOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: get-version
  docker-scan:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerBuildScan.yml@0.3.0
    with:
      dockerfilePath: 'docker/Dockerfile'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    needs: get-version
  docker-build-publish:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerBuildPublish.yml@0.3.0
    with:
      dockerfilePath: 'docker/Dockerfile'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [docker-lint,sonar-scan,docker-scan]
  update-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/updateVersion.yml@0.3.0
    with:
      gitUsername: 'grababyte'
      gitEmail: 'grababyte@github.com'
      metadataFile: 'metadata.json'
      metadataPath: .
    needs: docker-build-publish
